# Generated by Django 2.2 on 2021-02-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('altcontact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('department', models.CharField(default='Security', max_length=50)),
                ('CenterDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Center')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='MemberTemporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberTypeDetails', models.CharField(default='Sewadaar', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('altcontact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('department', models.CharField(default='Security', max_length=50)),
                ('CenterDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Center')),
            ],
            options={
                'verbose_name': 'MemberTemporary',
                'verbose_name_plural': 'MemberTemporarys',
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MemberType',
                'verbose_name_plural': 'MemberTypes',
            },
        ),
        migrations.CreateModel(
            name='SecurityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SecurityPost',
                'verbose_name_plural': 'SecurityPosts',
            },
        ),
        migrations.CreateModel(
            name='TransactionTemporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('MemberDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.MemberTemporary')),
            ],
            options={
                'verbose_name': 'TransactionTemporary',
                'verbose_name_plural': 'TransactionTemporarys',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('outtime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('TRAN', 'Transit'), ('INACT', 'InActive')], default='ACT', max_length=50)),
                ('misc', models.TextField(blank=True)),
                ('MemberDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Member')),
                ('SecurityPostDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.SecurityPost')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='MemberTypeDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.MemberType'),
        ),
    ]
