# Generated by Django 2.2 on 2021-01-30 06:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
            },
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')], default='M')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('altcontact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('department', models.CharField(default='Security', max_length=50)),
                ('CenterDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Center')),
            ],
            options={
                'verbose_name': 'MemberList',
                'verbose_name_plural': 'MemberLists',
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MemberType',
                'verbose_name_plural': 'MemberTypes',
            },
        ),
        migrations.CreateModel(
            name='SecurityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SecurityPost',
                'verbose_name_plural': 'SecurityPosts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('MemberDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.MemberList')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='memberlist',
            name='MemberTypeDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.MemberType'),
        ),
    ]
