# Generated by Django 2.2 on 2021-01-30 06:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='altcontact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')], default='Male'),
        ),
    ]
