# Generated by Django 2.2 on 2021-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20210130_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
