# Generated by Django 2.2 on 2021-01-30 08:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_auto_20210130_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberListOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberTypeDetails', models.CharField(default='Sewadaar', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('altcontact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('department', models.CharField(default='Security', max_length=50)),
                ('CenterDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Center')),
            ],
            options={
                'verbose_name': 'MemberListOpen',
                'verbose_name_plural': 'MemberListOpens',
            },
        ),
        migrations.CreateModel(
            name='TransactionOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('MemberDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.MemberListOpen')),
            ],
            options={
                'verbose_name': 'TransactionOpen',
                'verbose_name_plural': 'TransactionOpens',
            },
        ),
    ]
